### PR TITLE
Add alias for multi-line padding workaround

### PR DESCRIPTION
**Pull request by FranzSkuffka**
Re-did #273 after test was failing.

-  Add mixin
-  Add test and fixtures
-  Add description

### CODE REVIEW

**Comment by jenius** [comment]
Nice, this looks good. What is browser support like for this? And would you be willing to also add documentation for this to axis' docs site? Also ping @dbox for comment :+1:

**Comment by FranzSkuffka** [comment]
[IE says nope](http://caniuse.com/#feat=css-boxdecorationbreak). Source: caniuse
It works with background only, not with borders i am afraid.

Currently on the docs :+1: Does this look good?
image

**Comment by jenius** [comment]
Looks good. I think my only concern with this is that it's a one-line thing, so I'm not sure how useful an alias is since you could probably type the original declaration with fewer characters.

**Comment by FranzSkuffka** [comment]
1. I have been checking [this article](https://css-tricks.com/multi-line-padded-text/) by Chris Coyier and this seems to be the most sensible solution for the problem. There are several others available and neither `box-decoration-break: clone;` nor the other solutions are intuitive. Once some other technique turns out to be better we can possibly just drop-in the replacement.

2. I was looking at `open-type-ligatures` and figured `multi-line-padding` is justified too. Both shorten a longer expression and make it more semantically accessible imo.

**Comment by FranzSkuffka** [comment]
bumpity

**Comment by dbox** [comment]
Sorry, I missed this one. LGTM!

**Pull request merged**
