### PR TITLE
Add material design shadows

### PR DESCRIPTION
**Pull request by FranzSkuffka**
Converted @dbox awesome material design shadows.
Closing https://github.com/jescalan/axis/issues/277

Tasks:
- Add stylus source & link in index
- Add tests & fixtures
- Add visual test section

### CODE REVIEW

**Comment by FranzSkuffka** [comment]
The failing test is unrelated.

**Comment by FranzSkuffka** [comment]
Will submit a PR to the docs asap, my university network is blocking git ports. :watman:

**Comment by dbox** [comment]
Thanks for doing! My 2 notes would be:

1. I don't think we have to add an entire category for shadows. It can live in `utilities` or `layout`.
2. We need to format the comments to be more consistent with axis code comments, not the sassdocs style.

@jescalan can be the final authority!

**Comment by FranzSkuffka** [comment]
Ah, I see
1. I was looking at the structure and sorted it in after gradients. I certainly don't view it as a utility or layout tool.
2. Agreed, I did not want to remove the annotations but just saw that the params info is inside roots-www.

@jescalan What do you think about the category-issue? Will open a new PR once all required changes are clear.

**Comment by jescalan** [comment]
Honestly, I'm not sure if a feature like this belongs in axis. It's usage is limited narrowly to one specific design style, whereas most of the other utilities we have here are design-agnostic and could be used across any site. I think it's a great utility to have around if you are using material design, I'm just not sure it belongs in axis -- it might fit better in a material design UI library.

**Comment by dbox** [comment]
I think the material name can be a little misleading. Yes, that's where the shadows came from. But, the Axis table mixin was ported directly from bootstrap as well. 

IMHO these are just easy shortcuts to creating beautiful dropshadows. I wouldn't say this is limited to one design style.  Material design doesn't get © on dropshadows.

Honestly doesn't bother me one way or another if it gets added. Just my .02.

**Comment by FranzSkuffka** [comment]
> Material design doesn't get © on dropshadows

Again, referring to https://github.com/jescalan/axis/issues/277

I will file a new PR that levels out the bumps mentioned:
- Sassdocs / Axis Docs style
- naming ~~material~~

**Comment by dbox** [comment]
@jescalan has final say, so better hold off for now

**Comment by jescalan** [comment]
I would still vote 🚫 -- I just don't see this having many use cases outside of material design. But if anyone else wants to chime in and give a 👍 then I might be convinced.

**Comment by dbox** [comment]
👌

**Comment by FranzSkuffka** [comment]
I still think axis lacks some shadow helpers / utils.
@jescalan what are your thoughts on this and what are the requirements for a tool like this?

**Comment by FranzSkuffka** [comment]
@jescalan do you welcome a pull request for drop shadows & presets and what would the requirements be?

**Comment by jescalan** [comment]
Drop shadows don't strike me as basic UI elements or common utilities...

**Pull request closed without merging**
