### PR TITLE
add static positioning mixin

### PR DESCRIPTION
**Pull request by bkuri**
Kind of surprised that this isn't in nib and/or axis, but whatever. It does add an extra `position: static` CSS statement, but sometimes it might be desirable. I personally did it because I prefer one-liners. :+1: 

I also fixed indentation on the tests (coffeelint was bugging me to fix it).

### CODE REVIEW

**Comment by bkuri** [comment]
@jescalan It might be a good idea to omit the `position: static` statement altogether when compiling the CSS. Is that a possibility?

**Comment by jescalan** [comment]
Sure, you'd just have to use a different mixing than the `-pos` one. I think this looks good as-is, but if you want to try to make that change let me know. Otherwise ready to merge!

**Comment by bkuri** [comment]
@jescalan if you think that an explicit statement is better then I say go for it. I can't seem to be able to make up my mind. :)

**Comment by dbox** [comment]
@bkuri out of pure curiosity can you tell me a use-case for position static?

**Comment by bkuri** [comment]
@dbox static positioning is the default positioning type. So an explicit static statement would be useful if you would like to override a previous non-default cascading statement (i.e. `position: absolute`). For example:
```styl
.test
  absolute()

  .child
    static top 10px left 10px
```
... which would translate to:
```css
.test {
  position: absolute;
}
.test .child {
  position: static;
  left: 10px;
  top: 10px;
}
```

I think it just looks better to have top/left in a single line like that. Whether axis should add the explicit `position: static` statement, however, is debatable.

**Comment by jescalan** [comment]
Well if the only use case you have in mind is to override another position attribute, that seems like an easy decision: yes.

Also just curious, do a lot of people use `top`, `left`, etc with `position: static`? I personally consider this an antipattern, but I guess some people must do it anyway.

**Comment by bkuri** [comment]
@jescalan well, `static` is the default positioning mode, so I guess one could argue that *a lot* of people use it like that, albeit implicitly. ;)

Ultimately what I'm really looking for is a mixin that would allow me to write positioning one-liners such as this:
```styl
.test
  place <top> <right> <bottom> <left>
```
The main reason why I would like to do that is because I like to order my statements alphabetically, so a one liner like the above would make things a lot tidier in those cases. For instance:

Without the mixin (notice the `size` mixin getting in the way):
```styl
.test
  border 1px solid blue
  border-radius 3px
  color white
  cursor pointer
  font-size 1em
  font-weight bold
  left 390px
  size 190px, 20px
  top 0
```

With the mixin (denser and cleaner FTW):
```styl
.test
  border 1px solid blue
  border-radius 3px
  color white
  cursor pointer
  font-size 1em
  font-weight bold
  place top 0 left 390px
  size 190px, 20px
```

So that's my main motivation behind using `static` for this kind of thing, although a completely new mixin like `place` would be just fine if you feel like adding `position: static` is just too explicit (which I guess it would be most of the time).

Does that make sense?

**Comment by dbox** [comment]
Maybe I'm still being confused, but `left` and `top` doesn't work with `static` ...

**Comment by jescalan** [comment]
It does, it's just a really bad practice and produces very strange behavior

**Comment by dbox** [comment]
http://codepen.io/dbox/pen/RRZRYb

**Comment by bkuri** [comment]
@dbox I was looking for a standardized way to set positioning elements, which is why I initially thought that using `static` (which I know does nothing on its own) would be a good idea, but I guess it's a bit too convoluted in retrospect. ;)

I'll fall back to using `absolute` and `relative`, then. I do think it might be beneficial to use `static()` as a shortcut for `position: static`, though. I'll make the changes and submit them later if that's OK. :+1:

**Pull request closed without merging**
